name: image-extractor-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12
  - fastai
  - albumentations
  - opencv
  - numpyßß
  - pandas
  - pip
  - pip:
    - tensorboard
    - fiftyone
    - fiftyone-brain
    - fastapi
    - timm
    - uvicorn
    - python-multipart
    - transformers
    - accelerate
    - torch
    - torchvision
    - torchaudio
    - umap-learn
    - open_clip_torch
    - scikit-learn

    